doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        driver: pdo_pgsql

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            CategoryId: App\Infrastructure\Game\DoctrineCustomType\CategoryIdType
            GameId: App\Infrastructure\Game\DoctrineCustomType\GameIdType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Game:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Game/Model'
                prefix: 'App\Domain\Game\Model'
                alias: Game
