version: '3.8'

services:
  micro1_nginx:
    build: nginx
    working_dir: /www
    volumes:
      - ./../code:/www:delegated
    ports:
      - "8082:80"
    depends_on:
      - micro1_fpm

  micro1_fpm:
    build: php
    working_dir: /www
    volumes:
      - ./../code:/www:delegated
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - micro1_postgres

  micro1_postgres:
    image: postgres:12.7-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=micro1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "15432:5432"
